/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppTabs: typeof import('./components/AppTabs.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBox: typeof import('./components/TheBox.vue')['default']
    TheBoxCitiesSmall: typeof import('./components/TheBoxCitiesSmall.vue')['default']
    TheBoxDatesSmall: typeof import('./components/TheBoxDatesSmall.vue')['default']
    TheBoxSmall: typeof import('./components/TheBoxSmall.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHomeHero: typeof import('./components/TheHomeHero.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheTopBar: typeof import('./components/TheTopBar.vue')['default']
    TheTravelFilter: typeof import('./components/TheTravelFilter.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
